12-django/mysite/movie/urls.py
from django.urls import path
from .views import MovieList, MovieDetail, MovieCategory, MovieLanguage,MovieSearch

app_name = 'movie'

urlpatterns = [
  path('', MovieList.as_view(),name='movie_list'),
  path('<slug:slug>', MovieDetail.as_view(), name='movie_detail'),
  path('category<str:category>', MovieCategory.as_view(),name='movie_category'),
  path('language/<str:language>', MovieLanguage.as_view(), name='movie_language'),
  path('search/', MovieSearch.as_view(), name='movie_search'),
]

12-django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

from movie.views import HomeView

urlpatterns = [
    path('', HomeView.as_view()),
    path('admin/', admin.site.urls),
    path('movies/', include('movie.urls',namespace = 'movies')),
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

12-django/mysite/movie/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

CATEGORY_CHOICES = {
    ('A','Action'),
    ('D','Drama'),
    ('C','Comedy'),
    ('R','Romance'),
    ('F','Fiction')
}


LANGUAJES_CHOICES = {
    ('EN','English'),
    ('ES','Espanish'),
    ('GR','German'),
}


STATUS_CHOICES = {
    ('RA','Recently Added'),
    ('MW','Most Watched'),
    ('TR','Top Rated')
}

#Model
class Movie(models.Model):
    title = models.CharField(max_length=128)
    description  = models.TextField(max_length=256)
    image  = models.ImageField(upload_to='movies')
    category = models.CharField(choices=CATEGORY_CHOICES,max_length=1)
    language = models.CharField(choices=LANGUAJES_CHOICES,max_length=2)
    status = models.CharField(choices=STATUS_CHOICES,max_length=2)
    year = models.DateField()
    trailer = models.URLField(default='')
    slug = models.SlugField(blank=True, null=True)
    views_count = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Movie, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

12-django/mysite/movie/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Movie

# Create your views here.
class HomeView(ListView):
  model = Movie
  template_name = 'movie/home.html'

  def get_context_data(self, **kwargs):
    context = super(HomeView, self).get_context_data(**kwargs)
    context['top_rated'] = Movie.objects.filter(status = 'TR')
    context['most_watched'] = Movie.objects.filter(status = 'MW')
    context['recently_added'] = Movie.objects.filter(status = 'RA')
    context['espanish'] = Movie.objects.filter(language = 'ES')
    context['english'] = Movie.objects.filter(language = 'EN')
    context['german'] = Movie.objects.filter(language = 'GR')
    return context

class MovieList(ListView):
  model = Movie
  paginate_by = 4

class MovieDetail(DetailView):
  model = Movie

  def get_object(self):
    object = super(MovieDetail, self).get_object()
    object.views_count += 1
    object.save()
    return object

class MovieCategory(ListView):
  model = Movie
  paginate_by = 4
  template_name = 'movie/movie_category.html'

  def get_queryset(self):
    self.category = self.kwargs['category']
    movies = Movie.objects.filter(category = self.category)
    return movies

  def get_context_data(self, **kwargs):
    context = super(MovieCategory, self).get_context_data(**kwargs)
    context['movie_category'] = self.category
    return context

class MovieLanguage(ListView):
  model         = Movie
  paginate_by   = 4
  template_name = 'movie/movie_language.html'

  def get_queryset(self):
    self.language = self.kwargs['language']
    movies = Movie.objects.filter(language=self.language)
    return movies

  def get_context_data(self, **kwargs):
    context = super(MovieLanguage, self).get_context_data(**kwargs)
    context["movie_language"] = self.language
    return context

class MovieSearch(ListView):
  model         = Movie
  paginate_by   = 4
  template_name = 'movie/movie_search.html'

  def get_queryset(self):
    query = self.request.GET.get('q')
    if query:
      object_list = Movie.objects.filter(title__icontains=query)
    else:
      object_list = self.model.objects.none()
    return object_list

12-django/mysite/movie/templates/movie/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} [Movie App Django] {% endblock title%}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8">
    <img src="{% static 'imgs/banner.png' %}" class="img-fluid mt-5 mb-5">
    <h3 class="text-info h4">Recently addded</h3>
    <hr>
    <div class="owl-carousel owl-theme">
      {% for movie in recently_added%}
      <div class="card mb-5">
        <img src="{{movie.image.url}}" class="img-card-top" alt="{{movie.title}}" />
      </div>
      {% endfor%}
    </div>
    <h3 class="text-info h4">Most watched</h3>
    <hr>
    <div class="owl-carousel owl-theme">
      {% for movie in most_watched%}
      <div class="card mb-5">
        <img src="{{movie.image.url}}" class="img-card-top" alt="{{movie.title}}" />
      </div>
      {% endfor%}
    </div>
    <h3 class="text-info h4">Top reted</h3>
    <hr>
    <div class="owl-carousel owl-theme">
      {% for movie in top_rated%}
      <div class="card mb-5">
        <img src="{{movie.image.url}}" class="img-card-top" alt="{{movie.title}}" />
      </div>
      {% endfor%}
    </div>
    <h3 class="text-info h4">Espanish</h3>
    <hr>
    <div class="owl-carousel owl-theme">
      {% for movie in espanish%}
      <div class="card mb-5">
        <img src="{{movie.image.url}}" class="img-card-top" alt="{{movie.title}}" />
      </div>
      {% endfor%}
    </div>
    <h3 class="text-info h4">English</h3>
    <hr>
    <div class="owl-carousel owl-theme">
      {% for movie in english%}
      <div class="card mb-5">
        <img src="{{movie.image.url}}" class="img-card-top" alt="{{movie.title}}" />
      </div>
      {% endfor%}
    </div>
    <h3 class="text-info h4">German</h3>
    <hr>
    <div class="owl-carousel owl-theme">
      {% for movie in german%}
      <div class="card mb-5">
        <img src="{{movie.image.url}}" class="img-card-top" alt="{{movie.title}}" />
      </div>
      {% endfor%}
    </div>
  </div>
</div>
{% endblock content %}

12-django/mysite/movie/templates/movie/movie_category.html
{% extends 'base.html' %}
{% block title %} [Movie list Django] {% endblock title%}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center text-light mt-5"> <i class="fa fa-list"></i> Movie list</h1>
    <hr>
    <div class="row mb-5 justify-content-center">
      {% for movie in object_list%}
      <div class="col-sm-6">
        <div class="card mb-5" style="width: 18rem;">
          <img src="{{ movie.image.url }}" class="card-img-top" alt="{{ movie.title }}">
          <div class="card-body">
            <h5 class="card-title">{{ movie.title }}</h5>
            <hr>
            <p class="card-text"><small class="text-muted">{{ movie.year }}</small></p>
            <a href="{{ movie.id }}" class="btn btn-info btn-block">
              <i class="fa fa-film"></i>
              Movie Detail
            </a>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="col-sm-12">
        <div class="alert alert-info alert-block">
          <h4 class="alert-heading">Ops!</h4>
          There are no Movies in this Category
        </div>
      </div>
      {% endfor %}
    </div>
    {% if  is_paginated %}
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}

      {% for pages in page_obj.paginator.page_range %}
      {% if  page_obj.number == pages %}
      <li class="page-item active"><a class="page-link" href="#">{{ pages }}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{pages}}">{{ pages }}</a></li>
      {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    </ul>
    {% endif %}
  </div>
</div>
{% endblock content %}

12-django/mysite/movie/templates/movie/movie_detail.html
{% extends 'base.html' %} {% block content %}
<div class="row"></div>
<h2 class="text-center text-light mt-5 h3"> [ <i class="fa fa-video"></i> Movie Detail ] </h2>
<hr><br>
<div class="card mb-5">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{{ object.image.url }}" class="card-img" alt="{{ object.title }}">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ object.title }}</h5>
        <hr>
        <p class="card-text">
          {{ object.description }}
        </p>
        <p class="card-text"><small class="text-muted">{{ object.year }}</small></p>
        <p class="card-text">
          <span class="badge badge-warning">
            <i class="fa fa-clipboard-list"></i>
            {% if object.category == 'A' %}
            Action
            {% elif object.category == 'D' %}
            Drama
            {% elif object.category == 'C' %}
            Comedy
            {% elif object.category == 'R' %}
            Romance
            {% elif object.category == 'F' %}
            Fiction
            {% endif %}
          </span>
          <span class="badge badge-dark">
            <i class="fa fa-globe"></i>
            {% if object.language == 'EN' %}
            English
            {% elif object.language == 'ES' %}
            Spanish
            {% elif object.language == 'GR' %}
            German
            {% endif %}
          </span>
          <span class="badge badge-info">
            <i class="fa fa-bars"></i>
            {% if object.status == "RA" %}
            Recently Added
            {% elif object.status == "MW" %}
            Most Watched
            {% elif object.status == "TR" %}
            Top Rated
            {% endif %}
          </span>
          <span class="badge badge-dark"><i class="fa fa-eye"></i> {{ object.views_count }}</span>
        </p>
        <iframe width="560" height="315" src="{{ object.trailer }}" frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>


<!-- <div class="row justify-content-center">
  <div class="col-md-8">
    <h2>Movie list</h2>
    <h4>{{object.title}}</h4>
    <img src="{{object.image.url}}" alt="" />
    <div class="badge bade-primary">
      {{object.year}}
    </div>
    <p>{{object.description}}</p>
  </div>
</div> -->
{% endblock content %}

12-django/mysite/movie/templates/movie/movie_language.html
{% extends 'base.html' %}

{% block title %} [ Movie List ] {% endblock%}

{% block content %}
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1 class="text-center text-light mt-5 h3">
      [ <i class="fa fa-globe"></i>
      {% if movie_language == 'EN' %}
      English
      {% elif movie_language == 'ES' %}
      Spanish
      {% elif movie_language == 'GR' %}
      German
      {% endif %}
      Movies ] </h1>
    <hr><br>

    <div class="row mb-5">
      {% for movie in object_list %}
      <div class="col-sm-6">

        <div class="card mb-5" style="width: 18rem;">
          <img src="{{ movie.image.url }}" class="card-img-top" alt="{{ movie.title }}">
          <div class="card-body">
            <h5 class="card-title">{{ movie.title }}</h5>
            <hr>
            <p class="card-text"><small class="text-muted">{{ movie.year }}</small></p>
            <a href="/movies/{{ movie.id }}" class="btn btn-info btn-block">
              <i class="fa fa-film"></i>
              Movie Detail
            </a>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="col-sm-12">
        <div class="alert alert-info alert-block">
          <h4 class="alert-heading">Ops!</h4>
          There are no Movies in this Category
        </div>
      </div>
      {% endfor %}
    </div>

    {% if  is_paginated %}
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}

      {% for pages in page_obj.paginator.page_range %}
      {% if  page_obj.number == pages %}
      <li class="page-item active"><a class="page-link" href="#">{{ pages }}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{pages}}">{{ pages }}</a></li>
      {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    </ul>
    {% endif %}
  </div>
</div>
{% endblock content%}

12-django/mysite/movie/templates/movie/movie_list.html
{% extends 'base.html' %}
{% block title %} [Movie list Django] {% endblock title%}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8">
    <h1 class="text-center text-light mt-5"> <i class="fa fa-list"></i> Movie list</h1>
    <hr>
    <div class="row mb-5 justify-content-center">
      {% for movie in object_list%}
      <div class="col-sm-6">
        <div class="card mb-5" style="width: 18rem;">
          <img src="{{ movie.image.url }}" class="card-img-top" alt="{{ movie.title }}">
          <div class="card-body">
            <h5 class="card-title">{{ movie.title }}</h5>
            <hr>
            <p class="card-text"><small class="text-muted">{{ movie.year }}</small></p>
            <a href="{{ movie.slug}}" class="btn btn-info btn-block">
              <i class="fa fa-film"></i>
              Movie Detail
            </a>
          </div>
        </div>

      </div>
      {% endfor %}
    </div>
    {% if  is_paginated %}
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}

      {% for pages in page_obj.paginator.page_range %}
      {% if  page_obj.number == pages %}
      <li class="page-item active"><a class="page-link" href="#">{{ pages }}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{pages}}">{{ pages }}</a></li>
      {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    </ul>
    {% endif %}
  </div>
</div>
{% endblock content %}

12-django/mysite/movie/templates/movie/movie_search.html
{% extends 'base.html' %}

{% block title %} [ Movie List ] {% endblock%}

{% block content %}
<div class="row">
  <div class="col-md-8 offset-md-2">
    <h1 class="text-center text-light mt-5 h3">
      [ <i class="fa fa-search"></i>
      Results for '{{ request.GET.q }}' in Movies ] </h1>
    <hr><br>

    <div class="row mb-5">
      {% for movie in object_list %}
      <div class="col-sm-6">

        <div class="card mb-5" style="width: 18rem;">
          <img src="{{ movie.image.url }}" class="card-img-top" alt="{{ movie.title }}">
          <div class="card-body">
            <h5 class="card-title">{{ movie.title }}</h5>
            <hr>
            <p class="card-text"><small class="text-muted">{{ movie.year }}</small></p>
            <a href="/movies/{{ movie.id }}" class="btn btn-info btn-block">
              <i class="fa fa-film"></i>
              Movie Detail
            </a>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="col-sm-12">
        <div class="alert alert-info alert-block">
          <h4 class="alert-heading">Ops!</h4>
          No results found for '{{ request.GET.q }}'
        </div>
      </div>
      {% endfor %}
    </div>

    {% if  is_paginated %}
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}

      {% for pages in page_obj.paginator.page_range %}
      {% if  page_obj.number == pages %}
      <li class="page-item active"><a class="page-link" href="#">{{ pages }}</a></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{pages}}">{{ pages }}</a></li>
      {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    </ul>
    {% endif %}
  </div>
</div>
{% endblock content%}

12-django/mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %} {% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
</head>

<body class="bg-dark">
  {% include 'navbar.html' %}
  <div class="container mt-5">
    {% block content %} {% endblock content %}
  </div>
  <script src="{% static 'js/jquery.js'%}"></script>
  <script src="{% static 'js/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/owl.carousel.min.js'%}"></script>
  <script>
    $(".owl-carousel").owlCarousel({
      loop: true,
      margin: 10,
      nav: true,
      responsive: {
        0: {
          items: 1,
        },
        600: {
          items: 2,
        },
        1000: {
          items: 4,
        },
      },
    });
  </script>
</body>

</html>

12-django/mysite/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
  <a class="navbar-brand" href="/">
    <img src="{% static 'imgs/logo.png' %}" width="100px" />
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="/movies">
        <i class="fa fa-list"></i> Movie list</a>
    </div>

    <ul class="navbar-nav ml-md-auto mr-5">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-clipboard-list"></i> Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'movies:movie_category' 'A' %}">Action</a>
          <a class="dropdown-item" href="{% url 'movies:movie_category' 'D' %}">Drama</a>
          <a class="dropdown-item" href="{% url 'movies:movie_category' 'C' %}">Comedy</a>
          <a class="dropdown-item" href="{% url 'movies:movie_category' 'R' %}">Romance</a>
          <a class="dropdown-item" href="{% url 'movies:movie_category' 'F' %}">Fiction</a>
          {% comment %} <div class="dropdown-divider"></div> {% endcomment %}
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-globe"></i> Languages
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'movies:movie_language' 'EN' %}">English</a>
          <a class="dropdown-item" href="{% url 'movies:movie_language' 'ES' %}">Spanish</a>
          <a class="dropdown-item" href="{% url 'movies:movie_language' 'GR' %}">German</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'movies:movie_search' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" value='{{ request.GET.q }}'>
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">
        <i class="fa fa-search"></i>
      </button>
    </form>
  </div>
</nav>